### ISSUE TITLE
Disable BSpline Mesher option deprecated?

### ISSUE THREAD

**Issue by tpaviot** [tpaviot/oce#277]
From the current master, it appears that all  BRepMesh tests pass (on OSX):

<pre>
$ make test
[...]
      Start 16: BRepMeshTestSuite.testMeshBox
16/44 Test #16: BRepMeshTestSuite.testMeshBox ...................   Passed    0.02 sec
      Start 17: BRepMeshTestSuite.testMeshSphere
17/44 Test #17: BRepMeshTestSuite.testMeshSphere ................   Passed    0.36 sec
      Start 18: BRepMeshTestSuite.testMeshTorus
18/44 Test #18: BRepMeshTestSuite.testMeshTorus .................   Passed    3.41 sec
[...]
</pre>
So far, the latter used to fail. If other users can confirm this behavior, we could remove the "Disable BSpline Mesher" option from the cmake builder.

**Comment by thatcadguy** [comment]
Closing because @dbarbier merged this.
