### ISSUE TITLE
Weird BRepAlgoAPI_Cut behaviour

### ISSUE THREAD

**Issue by joukeHijlkema** [tpaviot/oce#410]
Hello all,

I've come across an issue with BRepAlgoAPI_Cut that I cant seem to resolve. I use the following code :

BRep_Builder builder;

TopoDS_Shape Main;
BRepTools::Read(Main,"Results/ErrorInCut_Main_3.000.brep",builder);
TopoDS_Shape Tool;
BRepTools::Read(Tool,"Results/ErrorInCut_Tool_4.000.brep",builder);

TopoDS_Shape Result;
BRepAlgoAPI_Cut mkCut(Main,Tool);
if (mkCut.IsDone()) {
  Result = mkCut.Shape();
} else {
  StdFail_NotDone::Raise("Cut construction failed");
}

It runs fine but the result is not what I expected, there is a trace of the tool on the main shape but no cut. The main shape is the result of a similar cut with the tool rotated 36° along the centerline of the main shape. I tried shape healing both in OCC and in Salome but to no avail. (The cutting operation works in Salome with the same brep files)

I attached images of the results. (I haven't figured out how to attach the brep files)

Please help, this is doing my head in.

![main](https://f.cloud.github.com/assets/404954/1224266/b68e7ce8-2744-11e3-8525-7a8c5dd0733b.png)
![result](https://f.cloud.github.com/assets/404954/1224267/b6a4d5c4-2744-11e3-9d06-d6f144e13cf9.png)
![tool](https://f.cloud.github.com/assets/404954/1224268/b6ba282a-2744-11e3-905f-26154b269b57.png)

**Comment by thatcadguy** [comment]
Seems to be a dead issue, closing. From the linked Google Groups conversation it appears the solution is to tighten up tolerances.
