### ISSUE TITLE
emscripten support

### ISSUE THREAD

**Issue by tpaviot** [tpaviot/oce#458]
emscripten (https://github.com/kripken/emscripten) enable javascript code generation from C/C++ code. This js code can be executed from Node.js or in any recent web browser.

Since OCE can be succesfully compiled with clang, it should be possible, in a first step, to port a very simple program (let's say create a box and measure its volume).

tp/emscripten (https://github.com/tpaviot/oce/tree/tp/emscripten) contains experiments related to this issue.

**Comment by chepilot** [comment]
Hi tpaviot,

I am trying to port oce with the newest Emscripten.
Following what you have done:
I generated a bunch of .a files or .so files for 64bit Unix under mac osx [in static or shared library mode]:
libTKBO.a		libTKFillet.a		libTKGeomBase.a		libTKOffset.a		libTKXMesh.a
libTKBRep.a		libTKG2d.a		libTKHLR.a		libTKPrim.a		libTKernel.a
libTKBool.a		libTKG3d.a		libTKMath.a		libTKShHealing.a
libTKFeat.a		libTKGeomAlgo.a		libTKMesh.a		libTKTopAlgo.a

Then following the tutorial in Emscripten
http://kripken.github.io/emscripten-site/docs/compiling/Building-Projects.html#building-projects-with-optimizations I use
$ .emcc -O1 [these .a files] -o oce.js 
for generating the .js file which I think would be the js version of oce.

However, llvm throw me the error 

ERROR: Linking globals named 'DISCRETALGO': symbol multiply defined!
Traceback (most recent call last):
  File "/emsdk_portable/emscripten/incoming/emcc", line 1197, in <module>
    shared.Building.link(linker_inputs, in_temp(target_basename + '.bc'), force_archive_contents=force_archive_contents)
  File "/emsdk_portable/emscripten/incoming/tools/shared.py", line 1397, in link
    assert os.path.exists(target) and (output is None or 'Could not open input file' not in output), 'Linking error: ' + output
AssertionError: Linking error: 

But it seems $.emcc -O1 [a single .a file] -o test.js would just generate the .js file.

I wonder first is my workflow correct? That is if let's say the oce.js is generated, it could be the js version of oce?
And if it could be the right path, how can I fix/ bypass this error?

Thank you.

**Comment by tpaviot** [comment]
It's been a while I worked on the emscripten port. As far as I remember, I did not manage to build an oce js library, I only managed to port some small executables. Try to start with examples that are provided with oce.
