### ISSUE TITLE
Error while Installing OCE (VS2008, Win64)

### ISSUE THREAD

**Issue by spirritus** [tpaviot/oce#473]
There is an error in the generated cmake_install.cmake:
1>CMake Error at cmake_install.cmake:48444 (FILE):
1>  file INSTALL cannot find "C:/data/oce-win-bundle-x64/Win64/lib/gl2ps.dll".
The line containing the gl2psd.lib is also wrong...

Quickfix: change fileending from .dll to .lib

**Comment by QbProg** [comment]
#575 solved the issue by removing the ambiguity: OCE_BUNDLE always builds the libs in the same way OCE does. 
Else one can build it's libraries by itself. Dlls and libs are optional now in the autoinstall phase.
