### ISSUE TITLE
OCE 0.16 cannot be built with nmake

### ISSUE THREAD

**Issue by viric** [tpaviot/oce#528]
Generating nmake mafiles with cmake on Windows doesn't work; there are some troublesome strange targets that seem planned only for the Visual Studio projects.

**Comment by QbProg** [comment]
I rebased the branch to current master , it seems to work good but I have some notes:
- /MP is useless in nmake because the compiler is called once per file. If you want to parallelize is better to use jom
- Precompiled.cpp get used correctly, but the build time seem not to be so much affected!
- I have to make sure that depending on ALL was not a requirement for msbuild based builds.

**Comment by tpaviot** [comment]
I rebased the branch on top of master to check if appveyor complains with these changes.

**Comment by thatcadguy** [comment]
This is still broken, the /MP option passed to rc kills compilation. Making a PR.

Also ref: https://groups.google.com/forum/#!msg/oce-dev/6UAq6kCLYT4/BFCvDF3C4p4J

**Comment by silentmissile** [comment]
not completely resolved until today 2015-12-30.

if the compile target is release, everything goes well

if the target is debug, in
oce-master\build\adm\cmake\TKService\CMakeFiles\TKService.dir\build.make
the lib file of freetype is missed
if the target is release, this file is not missed

so in debug mode, the nmake process would break at that point, the simplest way is to copy the the line from the file in the release build folder to the same place in debug folder

**Comment by QbProg** [comment]
yep, nmake support was broken a number of releases ago :) I used to support
it in first place, but I don't see the point of updating it anymore...
oce-win-bundle doesn't work too I guess.
I think the most appropriate way to re-enable it is to follow the mingw
definitions as it's a single-configuration generator too.

Il giorno mer 30 dic 2015 alle ore 15:10 silentmissile <
notifications@github.com> ha scritto:

**Comment by thatcadguy** [comment]
I actually don't know why I bothered with this in the first place, msbuild is better anyway. I guess I'll leave this open but I'm going to unassign myself as I don't see the point either.

**Comment by silentmissile** [comment]
in CMakeLists.txt line 437

find_library(FREETYPE_LIBRARY_DEBUG freetyped "Location of freetype debug library")

you want to find debug version of freetype lib

It's your policy, if you want to link to 3rd party libs release to release and debug to debug, it's ok.

but please add choice in Cmake-gui, or we can't give different lib files to different target

Also, this problem exists in not only nmake solution but also msbuild solution, the link procedure of TKService debug would fail, too

**Comment by silentmissile** [comment]
I test it, it's resolved in 0.17.1, what we need to care is only to assign suitable freetype.lib file for FREETYPE_LIBRARY and FREETYPE_LIBRARY_DEBUG

please close this issue
