### ISSUE TITLE
linking error, argument list too long.

### ISSUE THREAD

**Issue by sanderboer** [tpaviot/oce#536]
Hi,
on win 8.1 I tried various msys/mingw combos and they all fail at linking tkernel . 
ar: argument list too long.

Tips?

thx. Sander

ps msys2 is awesome. msys, upgraded, with a ported package management system (pacman)
http://sourceforge.net/projects/msys2

Came across it trying to build a new emacs:
http://sourceforge.net/p/emacsbinw64/wiki/Build%20guideline%20for%20MSYS2-MinGW-w64%20system/

cmake, qt, python, all in there.

**Comment by muschellij2** [comment]
FYI anyone who finds, this, I believe the argument is CMAKE_NEED_RESPONSE **not** (note the s in needs) CMAKE_NEEDS_RESPONSE as per https://github.com/msys2/MINGW-packages/blob/2cfdf054df2c826d7c61237ee5ac2453b0f3964d/mingw-w64-cmake/0003-Disable-response-files-for-MSYS-Generator.patch
