### ISSUE TITLE
Remove third-part locations for binary files

### ISSUE THREAD

**Issue by tpaviot** [tpaviot/oce#539]
Currently, some win32 binary package are available at https://code.google.com/p/oce-binaries (for oce-0.11 and oce-0.12). A google drive has also been set up (at http://bit.ly/1kvDoTN), currently empty.

Since it's possible to upload attachements for a release directly inside github, I suggest we remove this outdated/unused locations. As a consequence, we would only have a github account for our source code/binary packages/issues management.

**Comment by QbProg** [comment]
Done, google code removal will require some time (one month)
