### ISSUE TITLE
Issue CMake OCE-0.13

### ISSUE THREAD

**Issue by ScottDWagner** [tpaviot/oce#542]
I have and Issue with using CMake 2.8 when i set up the project. see image below. Its not finding the bundle source.
![oce-013-error](https://cloud.githubusercontent.com/assets/9826792/5114442/5907caa8-6ffe-11e4-96e0-928452ba739c.png)

**Comment by tpaviot** [comment]
OCE-0.13 is quite old. Issue closed, please reopen if ever the issue is still there in 0.16 or 0.17.
