### ISSUE TITLE
Compilation Error on Mingw32

### ISSUE THREAD

**Issue by DevJohan** [tpaviot/oce#545]
Hi,

This is related to #502 where among others OSD_File won't compile using Mingw on Windows.

I found that when you compile oce with mingw you have to specify a high enough _WIN32_WINNT define number or some functions used by oce won't be exported from windows.h and it's descendants.

To fix, the following 

#define _WIN32_WINNT 0x0XYZ
or
-D_WIN32_WINNT=0x0XYZ

should be included in the appropriate place where 0x0XYZ should be replaced with the appropriate number depending on which windows api version that should be used. I think the following list should be correct 

Windows XP                 0x0501,
Windows Server 2003  0x0502,
Windows Vista              0x0600,
Windows 7                    0x0601,
Windows 8                    0x0602,
Windows 8.1                 0x0603

and I at least for GetFileSizeEx(...), "_WIN32_WINNT >= 0x0500" must be satisfied
guess this could be included in "oce-config.h"

**Comment by QbProg** [comment]
could you please test the current master and see if it builds?

**Comment by yokoyamy** [comment]
Hi.
I’m facing similar problem at #580.

In my case massage shows `OSD_File.cxx:1650:46: error: 'GetFileSizeEx' was not declared in this scope`.

I tried your way to replace number in windows.h file.

From #if (_WIN32_WINNT >= 0x0400)

To #if (_WIN32_WINNT >= 0x0601)

However, It doesn’t work and still same error happens.

Do you have any idea?

**Comment by thatcadguy** [comment]
@yokoyamy Note that _WIN32_WINNT is defined in CMakeLists.txt for MinGW, it may be conflicting with what you try in winbase.h.
