### ISSUE TITLE
How to build for OS X?

### ISSUE THREAD

**Issue by marmalodak** [tpaviot/oce#549]
$ ./xcode.sh
    The file /Users/john/projects/opencascade/oce/scripts/adm/mac/xcd/OCCT.xcworkspace does not exist.

**Comment by dbarbier** [comment]
Hello, this script is not shipped by us.  There are instructions at https://github.com/tpaviot/oce/wiki/Build-(Mac-OSX) please use our mailing list if you have trouble.
