### ISSUE TITLE
math_Vector error help please!!

### ISSUE THREAD

**Issue by Nesty92** [tpaviot/oce#555]
Hello everyone!!   when I try to run a example get the following error
<b>/opt/oce/include/oce/math_Vector.hxx:273: error: expected unqualified-id before numeric constant
    Opposite Standard_EXPORT math_Vector ();</b>
with the libs compiled by the team freecad  same thing happens  any idea that it can be thank you very much

**Comment by dbarbier** [comment]
Hello,

Maybe something defines a cpp macro named Opposite to a numeric value (likely -1), there is not much we can do.

**Comment by Nesty92** [comment]
Thank you for responding this happens me to use the example occQt https://github.com/eryar/occQt available in linuxmint 17 based on ubuntu 14.04

**Comment by dbarbier** [comment]
Okay, `X11/Xlib.h` and `X11/X.h` define a bunch of macros with generic names which conflict with OCC methods (Opposite, but also Status, and maybe others).
You can try to add
```
#undef Status
#undef Opposite
```
between Qt includes and OCC ones; does anyone have a better idea?

**Comment by Nesty92** [comment]
Thank you for answering then I try your suggestion and posting the results

**Comment by Nesty92** [comment]
anyone have any other idea?

**Comment by Nesty92** [comment]
@dbarbier
#undef Opposite this is a solution!!! thanks you  ;)

**Comment by dbarbier** [comment]
Glad it worked for you.  This is not ideal, but unfortunately I do not see how to fix that on our side.
