### ISSUE TITLE
Documentation Mistakes

### ISSUE THREAD

**Issue by jmwright** [tpaviot/oce#556]
I've noticed a few documentation mistakes in gp_Vec.hxx

gp_Vec.hxx, line 162, for SquareMagnitude - //!Adds two vectors

gp_Vec.hxx, line 186, for Subtracted - //!Multiplies a vector by a scalar

gp_Vec.hxx, line 200, for Multiplied - //!Divides a vector by a scalar

**Comment by tpaviot** [comment]
Fixed by PR #557
