### ISSUE TITLE
PYOCC ON LINUX ON PYTHONANYWHERE

### ISSUE THREAD

**Issue by pyenthu** [tpaviot/oce#565]
Is there any convenient way to install PYOCC on PYTHONANYWHERE? Sudo and get is not allowed. 
I have a working version on my windows laptop but installation on Linux on the cloud is required to create a webapp.

**Comment by tpaviot** [comment]
Please post this issue to the pythonocc issue tracker https://github.com/tpaviot/pythonocc-core/issues
