### ISSUE TITLE
CMake Error: CMake was unable to find a build program corresponding to "MSYS Makefiles".  

### ISSUE THREAD

**Issue by 3wwebdev** [tpaviot/oce#578]
Hi

I am getting this error:
CMake Error: CMake was unable to find a build program corresponding to "MSYS Makefiles".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
CMake Error: CMake was unable to find a build program corresponding to "MSYS Makefiles".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
CMake Error: Error required internal CMake variable not set, cmake may be not be built correctly.
Missing variable is:
CMAKE_C_COMPILER_ENV_VAR
CMake Error: Error required internal CMake variable not set, cmake may be not be built correctly.
Missing variable is:
CMAKE_C_COMPILER
CMake Error: Could not find cmake module file: C:/OCE/0.16.1/build/CMakeFiles/3.3.2/CMakeCCompiler.cmake
CMake Error: Error required internal CMake variable not set, cmake may be not be built correctly.
Missing variable is:
CMAKE_CXX_COMPILER_ENV_VAR
CMake Error: Error required internal CMake variable not set, cmake may be not be built correctly.
Missing variable is:
CMAKE_CXX_COMPILER
CMake Error: Could not find cmake module file: C:/OCE/0.16.1/build/CMakeFiles/3.3.2/CMakeCXXCompiler.cmake
CMake Error at CMakeLists.txt:20 (project):
  No CMAKE_C_COMPILER could be found.

  Tell CMake where to find the compiler by setting the CMake cache entry
  CMAKE_C_COMPILER to the full path to the compiler, or to the compiler name
  if it is in the PATH.

CMake Error at CMakeLists.txt:20 (project):
  No CMAKE_CXX_COMPILER could be found.

  Tell CMake where to find the compiler by setting the CMake cache entry
  CMAKE_CXX_COMPILER to the full path to the compiler, or to the compiler
  name if it is in the PATH.

CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
CMake Error: CMAKE_AR was not found, please set to archive program. 
Configuring incomplete, errors occurred!

I was following this https://github.com/tpaviot/oce/blob/master/BUILD.MINGWw64.md
and got to step 6 point 3 when the error shows in cmaker?
action taken at steps 1 to 6:
1, downloaded this http://mingw-w64.org/doku.php/download/mingw-builds

2, downloaded this http://sourceforge.net/projects/mingwbuilds/files/external-binary-packages/msys%2B7za%2Bwget%2Bsvn%2Bgit%2Bmercurial%2Bcvs-rev13.7z/download

3, downloaded this https://cmake.org/files/v3.3/cmake-3.3.2-win32-x86.exe

4, https://codeload.github.com/tpaviot/oce/zip/master

5, downloaded this https://codeload.github.com/QbProg/oce-win-bundle/zip/master

6, followed no. 6 points 1 to 2 and got error on point 3.

**Comment by thatcadguy** [comment]
You can just choose MinGW makefiles, that's what I always do. No need for Msys that I know of.
