### ISSUE TITLE
How to use conda to install opencascade_community_edition???

### ISSUE THREAD

**Issue by WBB-Badtaste** [tpaviot/oce#599]
As you can see, I have found the opencascade_community_edition, But I can't install it.
How can I do it?
If I wanna install opencascade_community_edition 0.16.1, How can I do that?

>wubinbindeMacBook-Air:getting_started Martin$  anaconda search -t conda opencascade_community_edition
Using Anaconda Cloud api site https://api.anaconda.org
Run 'anaconda show <USER/PACKAGE>' to get more details:
Packages:
     Name                      |  Version | Package Types   | Platforms      
     ------------------------- |   ------ | --------------- | ---------------
     jf/opencascade_community_edition |          | conda           | osx-64         
                                          : OpenCASCADE community edition
Found 1 packages
wubinbindeMacBook-Air:getting_started Martin$ anaconda show jf/opencascade_community_edition
Using Anaconda Cloud api site https://api.anaconda.org
Name:    opencascade_community_edition
Summary: OpenCASCADE community edition
Access:  public
Package Types:  conda
Versions:
   + 0.15.0
   + 0.16.0
   + 0.17.0
   + 0.16.1
   + 0.17

To install this package with conda run:
     conda install --channel https://conda.anaconda.org/jf opencascade_community_edition
wubinbindeMacBook-Air:getting_started Martin$ conda install --channel https://conda.anaconda.org/jf opencascade_community_edition
Fetching package metadata: ........
Error: No packages found in current osx-64 channels matching: opencascade_community_edition

You can search for this package on anaconda.org with

    anaconda search -t conda opencascade_community_edition

**Comment by thatcadguy** [comment]
`conda install -c https://conda.anaconda.org/dlr-sc oce`
https://anaconda.org/dlr-sc/oce
Please use the mailing list (https://groups.google.com/forum/#!forum/oce-dev) for questions in the future, thanks.
