### ISSUE TITLE
OCE 0.16.1 Tests segfaulting with GCC 6.0.0

### ISSUE THREAD

**Issue by hobbes1069** [tpaviot/oce#605]
I'm assuming this is a GCC 6.0 issue since this wasn't happening before. 

Here's the list of failed tests:
```
19:IGESImportTestSuite.testImportIGES_1
22:STEPImportTestSuite.testImportAP203_1
23:STEPImportTestSuite.testImportAP203_2
24:STEPImportTestSuite.testImportAP214_1
25:STEPImportTestSuite.testImportAP214_2
26:STEPImportTestSuite.testImportAP214_3
29:BRepOffsetAPITestSuite.testEvolvedShape
30:BRepOffsetAPITestSuite.testOffsetBox
31:BRepImportTestSuite.testImportBRep1
32:BRepImportTestSuite.testImportBRep2
33:BRepImportTestSuite.testImportBRep3
34:BRepImportTestSuite.testImportBRep4
37:BRepMeshTestSuite.testMeshTorus
```
The full testlog is here:
https://dl.dropboxusercontent.com/u/34775202/LastTest.log

And the stack trace of one of the tests:
https://dl.dropboxusercontent.com/u/34775202/BRepImport_test_gdb.txt

**Comment by thatcadguy** [comment]
Is GCC 6 even considered stable yet?

**Comment by hobbes1069** [comment]
I'd have to ask but Fedora Rawhide (future 24 version) is rebuilding all packages against it.

**Comment by hobbes1069** [comment]
I tried adding "-fno-delete-null-pointer-checks" to the test binaries per https://github.com/google/googletest/issues/705 but no luck, but I only added it to the binaries, not the test library.

**Comment by hobbes1069** [comment]
Adding "-fno-delete-null-pointer-checks" as a global CXXFLAG worked but it's still just a work around.

**Comment by tpaviot** [comment]
@hobbes1069 it might be related to issue #604 and #576 . clang used to perform optimizations that makes oce segfault, maybe it's the same with recent gcc versions. Don't know if it's possible to cherry-pick commit 61cb965b9ffeca419005bc15e635e67589c421dd that fixes this issue over oce-0.17 but i's worth trying.

**Comment by hobbes1069** [comment]
It applied cleanly to 0.17 so I'm doing a test build however Fedora is still stuck on 0.16.1 until smesh is updated. Hopefully it applies cleanly to it as well. Thanks for the pointer.

**Comment by hobbes1069** [comment]
On a side note, does this fix create an ABI change? If so I'll need to rebuild all dependencies.

**Comment by hobbes1069** [comment]
I went ahead and did a new build. Everything seems OK but the ARM build is still going, but that's to be expected.
