### ISSUE TITLE
set RPATH or install name for all installed libs?

### ISSUE THREAD

**Issue by davydden** [tpaviot/oce#610]
i would like to install OCE on Darwin in custom location and use it without setting DYLD_LIBRARY_PATH. My understanding is that one of these solutions would do it:
(i) all libs have install names as full path: (/path/to/oce/lib/libABC.dylib) instead of libABC.dylib
(ii) or there is RPATH set.

Is there any `-DOCE_XYZ` CMake flag that would help to achieve this?

**Comment by jf---** [comment]
hi @davydden ,

IIRC there's a difference in [how .dylib's are built]() with cmake 3.x.x and 2.8.x
Are you on a recent version of cmake?

**Comment by davydden** [comment]
@jf--- yes, I am on 3.xx.

**Comment by davydden** [comment]
nevermind, i ended up using a python script with `install_name` tool on OSX.
