### ISSUE TITLE
Hide the seam edges and only show the non-seam edges in the OpenGL render

### ISSUE THREAD

**Issue by asmwarrior** [tpaviot/oce#614]
Hi, is it possible(or is there any option) to just filter out the seam edges and only shows the non-seam edges in the render output?
For me, I would like to draw some technical drawings(I would like to put the drawings in some papers or books), this is some operations like a screen shot on the FreeCAD's 3D view, but the seam lines are not needed from my point of view, is there any options in OCE, because I see in the FreeCAD's forum(see this post: [seams on round objects](http://forum.freecadweb.org/viewtopic.php?f=3&t=14022)), they said that they can't control the rendering output, but only the geometry kernel can do this. Thanks.

**Comment by thatcadguy** [comment]
this isn't an issue/bug; use the mailing list for usage questions: https://groups.google.com/forum/#!forum/oce-dev
Or OpenCASCADE's forum
