### ISSUE TITLE
Instalation problem

### ISSUE THREAD

**Issue by gsibenik** [tpaviot/oce#620]
Hello,
i am an architect and need to install OCE. I tried with MinGW with the instructions from https://github.com/tpaviot/oce/blob/master/BUILD.MINGWw64.md
I didnt have an option to check OCE_USE_BUNDLE_SOURCE in cmake.
Got it after changing the folder name. As I could realised there are some problems with some paths and folder names, but I am not sure in which way to change them so they work.
Can you please help me with this problem, I am new in the field and I get a lot of other issues in cmake after that step?

If you need some more input from me I will be glad to send it.
Thank you!

**Comment by thatcadguy** [comment]
See https://github.com/QbProg/oce-win-bundle. If you put that in the same directory as the OCE files, CMake should be able to configure and compile everything in one shot.
