### ISSUE TITLE
Problems when building OCE

### ISSUE THREAD

**Issue by zack11235** [tpaviot/oce#622]
Hello,
When trying to build OCE on Windows as described here (https://github.com/tpaviot/oce/wiki/Build). First cmake requires Freetype library, so I downloaded the binaries online from http://gnuwin32.sourceforge.net/packages/freetype.htm and used freetype-binaries\include for FREETYPE_INCLUDE_DIRECTORY_ft2build and freetype-binaries\include\freetype2 for FREETYPE_INCLUDE_DIRECTORY_freetype2 and also \freetype-binaries\lib\freetype.lib for FREETYPE_LIBRARY and unchecked FREETYPE_LIBRARY_DEBUG.  When cmake finishes generating I was not able to find the OCE-libraries.cmake and OCE-libraries-release.cmake files that I will need later on when build OccJava.  Then went on as suggested in the link and build the OCE.sln with my selected generator (Visual Studio 10 Win 64 - Release). 
After a long build I get errors related to FreeTypeLibrary!

Regards,
Mahmoud Zaki

**Comment by zack11235** [comment]
in a nutshell I have two problems:
- I do not have OCE-libraries.cmake and OCE-libraries-release.cmake files in the generated code.
- I do not know what do to do with freetype libraries!

**Comment by thatcadguy** [comment]
Don't need to double post on this and the group, look up oce-win-bundle, it's all you need.

**Comment by zack11235** [comment]
Sorry I posted here because I thought there is not the right place to post. 

Thank you!
