### ISSUE TITLE
How to quickly load/save STL meshes?

### ISSUE THREAD

**Issue by HuguesDelorme** [tpaviot/oce#628]
Hello dear OCE users,

Just to let you know about the existence of the gmio project.
  **gmio is a free and open-source C library** providing I/O support for the STL file format(more CAD formats in next releases).
- it's **fast**: gmio is x500 times faster to write binary STL than OpenCascade, see [benchmarks](https://github.com/fougue/gmio/wiki/4.-Benchmarks)
- it's **feature-rich**: ascii/binary, little/big endian, format probing, infos retrieval, ... see [gmio_stl](http://www.fougue.pro/docs/gmio/0.3/group__gmio__stl.html#details)
- it's **reusable**: based on streams, seamless integration with OpenCascade, see [gmio_support](http://www.fougue.pro/docs/gmio/0.3/group__gmio__support.html#details)
- it's **portable**: C90 conformant but it can use recent C features if available

**OCE could benefit improved STL format support with gmio**, just try it!
`>>` https://github.com/fougue/gmio
`>>` [v0.3.0 ZIP archive](https://github.com/fougue/gmio/archive/v0.3.0.zip) or `git clone https://github.com/fougue/gmio.git`
`>>` [Build instructions](https://github.com/fougue/gmio/wiki/2.-Build-instructions)
`>>` [Examples of use](https://github.com/fougue/gmio/wiki/3.-Getting-started)

**Comment by thatcadguy** [comment]
This isn't an issue, post to the mailing list if you want.
