### ISSUE TITLE
FreeType, FreeImage, Gl2ps and CMAKE_CONFIGURATION_OPTIONS

### ISSUE THREAD

**Issue by Fredounet** [tpaviot/oce#630]
I'm recompiling OCE on MSYS2 (Mingw-64b) but encountered some strange error with Cmake.
When I added the checked options, Gl2ps and FreeImage then `configure` failed with:

`get_filename_component has incorrect number of arguments.`

This seems to be about the Debug paths. Looking at FreeImage, a if statement is used that tests `CMAKE_CONFIGURATION_OPTIONS`. I eventually figured I should have done a 'delete cache' before reconfiguring (see message below). Grrr.

But, looking at this in more detail, I couldn't find `CMAKE_CONFIGURATION_OPTIONS` defined anywhere before the first line where it is tested. Wasn't maybe `CMAKE_CONFIGURATION_TYPES` meant to be used instead? What kind of flag is this supposed to be?

**Comment by Fredounet** [comment]
Ok. Forget about the error. I had to do a "delete cache" before recompiling with the flags Freeimage and Gl2ps on. 
Nonetheless, I still find the `CMAKE_CONFIGURATION_OPTIONS` flag rather odd.

**Comment by tpaviot** [comment]
@Fredounet does it work now ? if yes, can you please close the issue ?

**Comment by ArvinShaffer** [comment]
i get the same error, can you tell me how to solve it
