### ISSUE TITLE
Compiling with MSYS2 Mingw64 (or Mingw32)

### ISSUE THREAD

**Issue by Fredounet** [tpaviot/oce#631]
**NOTE: This may not be complete, but almost. I'll remove this message once I'm done.**
NOTE: The process below should work just as well with Mingw32. The difference is that you need to replace `x86_64` by `i686` in the `pacman` commands, and open `mingw32.exe` instead of `mingw64.exe` for the actually compilation procedure. The MSYS2 and mingw32.exe may also be in a folder `C:/msys32/` instead of `C:/msys64/`.
## MSYS2:

Install MSYS2 by following the procedure at: http://msys2.github.io/
## QT5 and compilation tools:

Open MSYS2 (MSYS2.exe, likely located in `C:/msys64/`) and install qt5 
`pacman -Sy mingw-w64-x86_64-qt5`

Still in MSYS2, install cmake, git (sys/git), make (sys/make), toolchain (includes gcc), 

```
pacman -Sy git
pacman -Sy make
pacman -Sy cmake
pacman -Sy ming-w64-x86_64-toolchain
```
## OCE

Still in MSYS2, continue by installing libraries that you will need: tcl, tk, freeimage, gl2ps,freetype, libpng (and boost, opencollada, swig). This list make be too extensive (cannot recall if tcl and tk are actually required here).

```
pacman -Sy mingw-w64-x86_64-freeimage
pacman -Sy mingw-w64-x86_64-gl2ps
pacman -Sy mingw-w64-x86_64-freetype
pacman -Sy mingw-w64-x86_64-libpng
pacman -Sy mingw-w64-x86_64-tcl
pacman -Sy mingw-w64-x86_64-tk
```

Note that Freetype and libpng should already be installed with qt5. 

Close MSYS2, and open `mingw64.exe` (likely located in `C:/msys64/`, like MSYS2.exe).

Go to the folder `C:/msys64/`, and download OCE using git:

```
cd /c/msys64/
git clone https://github.com/tpaviot/oce.git
```
### Cmake

follow the "Building" section at https://github.com/tpaviot/oce/wiki/Build-%28MinGW-w64%29. 

**BUT**, you don't need to use the _Bundle_ as all those libraries are already available under MSYS2.
However, you must add to `CMAKE_NEED_RESPONSE=YES` to Cmake before launching the _Configure_. If you correct this after the error has occured (it's a "linking error, argument list too long" that happens after approx. 40% of the compilation ), then compilation will restart from scratch. So, I recommend adding this upfront, and not wait for the error. Otherwise, you'll have wasted a few hours.
When you _Configure_, use `MSYS Makefiles` and set `CMAKE_MAKE_PROGRAM` to `C:/msys64/usr/bin/make.exe`. The rest should be straight-forward.
Once _Configure_ is successful, run _Generate_ and finally close Cmake-gui.
### Make

cd into your build directory, and run `make`. 
Remember that it's probably a good idea to use `make -j4` (or more, if you have). 

As usual, compilation takes forever, but it goes smoothly, only 1 test failed at the very end (no big deal).

**Comment by Stinkfist0** [comment]
FYI, I recently made a simple dependency build script for IfcOpenShell for MSYS2 + MinGW which also includes very straightforward steps for building OCE too https://github.com/Tridify/IfcOpenShell/blob/msys/win/build-deps.sh

**Comment by Fredounet** [comment]
Nice.
What about the CMAKE_NEED_RESPONSE flag? You didn't need that?

**Comment by Stinkfist0** [comment]
Nope, so far everything has worked OK without it.

**Comment by nickoe** [comment]
Hi, I have been working on getting this to MSYS2 too. I have a PKGBUILD that is almost complete, I just need disable OCE_AUTOINSTALL_DEPENDENT_LIBS and then I think it is good to go. I also see that createprocess error sometimes. I don't understand the issue, it happens sometimes.

**Comment by thatcadguy** [comment]
@Fredounet Hi, if you fork the current master and add this guide as a readme (name it BUILD.MSYS2.md) or something like that, submit a PR and I'll merge.

**Comment by Fredounet** [comment]
@thatcadguy Done. Sorry for the delay.

**Comment by thatcadguy** [comment]
@Fredounet merged your PR

**Comment by mahaidong** [comment]
is it possible to set DRAW=Yes to compile DRAWEXE?

**Comment by may-tp** [comment]
`pacman -Sy ming-w64-x86_64-toolchain` should be `pacman -Sy mingw-w64-x86_64-toolchain`
