### ISSUE TITLE
Open CASCADE ver 6.9.0 merge into oce timescale

### ISSUE THREAD

**Issue by iras** [tpaviot/oce#633]
Hi @tpaviot,

this isn't an issue, more of a question. I'm compiling IfcOpenShell and _oce_ is a necessary dependency as you are aware. I get a warning about running an old version of Open Cascade within _oce_. When do you reckon Open Cascade ver 6.9.0 will be merged in _oce_? Many thanks.

`
...
[ 52%] Building CXX object CMakeFiles/IfcGeom.dir/tmp/ifc-open-shell/src/ifcgeom/IfcGeomFunctions.cpp.o
/tmp/ifc-open-shell/src/ifcgeom/IfcGeomFunctions.cpp:139:2: warning: #warning "You are linking against linking against an older version of Open CASCADE. Version 6.9.0 introduces various improvements with relation to boolean operations. You are advised to upgrade." [-Wcpp]
 #warning "You are linking against linking against an older version of Open CASCADE. Version 6.9.0 introduces various improvements with relation to boolean operations. You are advised to upgrade."
  ^
`

**Comment by Stinkfist0** [comment]
https://github.com/tpaviot/oce/issues/561
