### ISSUE TITLE
src/ShapeFix/ShapeFix_Face.cxx:1368]: (style) Redundant condition:

### ISSUE THREAD

**Issue by dcb314** [tpaviot/oce#637]
src/ShapeFix/ShapeFix_Face.cxx:1368]: (style) Redundant condition: !isAddNaturalBounds. 'isAddNaturalBounds || (!isAddNaturalBounds && nbInternal<nb)' is equivalent to 'isAddNaturalBounds || nbInternal<nb'

Source code is

   done = (done && (nb ==1 || (isAddNaturalBounds || (!isAddNaturalBounds && nbInternal <nb))));

**Comment by thatcadguy** [comment]
Thanks for reporting, but we usually don't make style changes like this as we only like to make necessary/critical changes.
