### ISSUE TITLE
Compiling kicad cmake error

### ISSUE THREAD

**Issue by ricksanchezc132** [tpaviot/oce#677]
==> Extracting sources...
  -> Creating working copy of kicad-source-mirror git repo...
Cloning into 'kicad'...
done.
Checking out files: 100% (3758/3758), done.
  -> Creating working copy of kicad-library git repo...
Cloning into 'kicad-libs'...
done.
Checking out files: 100% (8752/8752), done.
==> Starting pkgver()...
==> Updated version: mingw-w64-kicad-git r8608.1e35d4594-1
==> Starting build()...
CMake Error: CMake was unable to find a build program corresponding to "MSYS Makefiles".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
CMake Error: CMake was unable to find a build program corresponding to "MSYS Makefiles".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
CMake Error: CMAKE_AR was not found, please set to archive program.
-- Configuring incomplete, errors occurred!
==> ERROR: A failure occurred in build().
    Aborting...

**Comment by tpaviot** [comment]
@ricksanchezc132 you posted on the wrong project page.
