### ISSUE TITLE
Maybe a memory leak in Standard.cxx

### ISSUE THREAD

**Issue by labusi** [tpaviot/oce#736]
In the Standard.cxx file, I'd like to know whether or not there should be a "delete myFMMgr" in the if block, It seems a memory leak issue.
```c++
Standard_MMgrFactory::~Standard_MMgrFactory()
{
  if (  myFMMgr )
    myFMMgr->Purge(Standard_True);
}

```

**Comment by tpaviot** [comment]
Hard to say. ```cppcheck``` does not report any issue

**Comment by aothms** [comment]
This is actually documented:


> // Therefore holder currently does not call destructor of the memory manager 
> // but only its method Purge() with Standard_True.

https://github.com/tpaviot/oce/blob/oce/patches/src/Standard/Standard.cxx#L203

Has to deal with construction and destruction of static definitions in different compilation units.

**Comment by tpaviot** [comment]
Thank you @aothms
