### ISSUE TITLE
cpack installer does not inform you of where the binaries are installed [osx specific?]

### ISSUE THREAD

**Issue by jf---** [tpaviot/oce#75]
the installer provides no clue where the binaries are installed on the system, it would be comforting to get some feedback on that.
also, after building OCE, a nice .sh script is provided with all the nessecary OCC env vars.
perhaps after installing OCE, a text editor can be openend with these settings / README

**Comment by thatcadguy** [comment]
@jf--- Jelle, is this still an issue? This issue is rather old.

**Comment by jf---** [comment]
lets close it, thanks for the heads up Jacob...
